package hu.csabi.architecture.data.paging

import androidx.paging.ExperimentalPagingApi
import androidx.paging.LoadType
import androidx.paging.PagingState
import androidx.paging.RemoteMediator
import androidx.room.withTransaction
import hu.csabi.architecture.core.result.AppResult
import hu.csabi.architecture.data.local.ArchitectureDatabase
import hu.csabi.architecture.data.local.RemoteKeyEntity
import hu.csabi.architecture.data.local.RepoEntity
import hu.csabi.architecture.data.local.localNeedle
import hu.csabi.architecture.data.local.toEntity
import hu.csabi.architecture.data.remote.RepoRemoteDataSource
import hu.csabi.architecture.domain.model.SearchQuery

/**
 * Lesson 09 — the piece that makes paging offline-first.
 *
 * Division of labour, and it is strict:
 *  - the **PagingSource** (generated by Room) reads pages out of the database
 *  - this **RemoteMediator** notices the list ran out of local rows, fetches the next page
 *    and *writes it to the database*
 *
 * Nothing here returns data to the UI. The list updates because Room invalidates the paging
 * source when the table changes. Same rule as lesson 08: the network writes, the UI reads
 * storage — which is why scrolling a previously-loaded list works with no connection.
 */
@OptIn(ExperimentalPagingApi::class)
class RepoRemoteMediator(
    private val query: SearchQuery,
    private val remote: RepoRemoteDataSource,
    private val database: ArchitectureDatabase,
) : RemoteMediator<Int, RepoEntity>() {

    private val needle = query.localNeedle()

    /**
     * Called before the first load. `LAUNCH_INITIAL_REFRESH` hits the network once on open;
     * `SKIP_INITIAL_REFRESH` would show cached rows immediately and never refresh. The
     * freshness rule from lesson 08 decides, so a cold start on a plane shows the cache.
     */
    override suspend fun initialize(): InitializeAction {
        val key = database.remoteKeyDao().find(needle)
        val age = System.currentTimeMillis() - (key?.updatedAt ?: 0L)
        return if (key == null || age > CACHE_TTL_MILLIS) {
            InitializeAction.LAUNCH_INITIAL_REFRESH
        } else {
            InitializeAction.SKIP_INITIAL_REFRESH
        }
    }

    override suspend fun load(
        loadType: LoadType,
        state: PagingState<Int, RepoEntity>,
    ): MediatorResult {
        val page = when (loadType) {
            LoadType.REFRESH -> FIRST_PAGE

            // Search results have no "page before the first one". Saying so immediately is
            // what stops Paging from asking again on every scroll to the top.
            LoadType.PREPEND -> return MediatorResult.Success(endOfPaginationReached = true)

            LoadType.APPEND -> {
                val key = database.remoteKeyDao().find(needle)
                // A null nextPage means the previous append already hit the end.
                key?.nextPage ?: return MediatorResult.Success(endOfPaginationReached = true)
            }
        }

        return when (val result = remote.searchRepositoriesPage(query, page, PAGE_SIZE)) {
            // AppError is a Throwable, so the typed error travels into Paging's LoadState
            // unchanged and the UI can still tell a network failure from a rate limit.
            is AppResult.Failure -> MediatorResult.Error(result.error)

            is AppResult.Success -> {
                val repos = result.data.repos
                val loadedSoFar = page * PAGE_SIZE

                /**
                 * The GitHub search API never returns more than 1000 results, whatever
                 * `total_count` claims. Asking past that is a 422, so the cap has to be part
                 * of the end-of-pagination rule — exactly the kind of API-specific limit that
                 * belongs in the data layer and nowhere else.
                 */
                val reachableTotal = minOf(result.data.totalCount, MAX_SEARCH_RESULTS)
                val endReached = repos.isEmpty() || loadedSoFar >= reachableTotal

                /**
                 * One transaction for the whole write.
                 *
                 * Without it, a crash between clearing the old rows and inserting the new
                 * ones leaves an empty list with a stale key — and the paging source would
                 * emit that intermediate state to the UI, because Room invalidates per write.
                 */
                database.withTransaction {
                    if (loadType == LoadType.REFRESH) {
                        database.repoDao().deleteMatching(needle)
                        database.remoteKeyDao().delete(needle)
                    }
                    val now = System.currentTimeMillis()
                    database.repoDao().upsertAll(repos.map { it.toEntity(fetchedAt = now) })
                    database.remoteKeyDao().upsert(
                        RemoteKeyEntity(
                            queryKey = needle,
                            nextPage = if (endReached) null else page + 1,
                            totalCount = result.data.totalCount,
                            updatedAt = now,
                        ),
                    )
                }

                MediatorResult.Success(endOfPaginationReached = endReached)
            }
        }
    }

    companion object {
        const val PAGE_SIZE = 20
        private const val FIRST_PAGE = 1
        private const val MAX_SEARCH_RESULTS = 1_000
        private const val CACHE_TTL_MILLIS = 5 * 60 * 1000L
    }
}
